logging:
  file: ./logs/service.log
  level:
    root: info
    org.springframework: info
    br.com.whs.javamongo: info
    br.com.whs.javamongo.controller: debug
  pattern:
    file: "[%d{ISO8601}] %-5level %-40.40c{1.} : %m%ex%n"


spring:
  application:
    name: ${APPLICATION_NAME:java-mongo}
data:
  mongodb:
    uri: ${MONGODB_URI:mongodb://root:example@localhost:27017}

server:
  port: 8080

api:
  version: v1
