logging:
  file: ./logs/service.log
  level:
    root: info
    org.springframework: info
    br.com.kroton: info
    br.com.kroton.matricula.ms.http: debug
  pattern:
    file: "[%d{ISO8601}] %-5level %-40.40c{1.} : %m%ex%n"


spring:
  application:
    name: ${APPLICATION_NAME:java-mongo}
  profiles:
    active: "dev-local"

server:
  port: 8080

api:
  version: v1

---
  
spring:
  profiles: "dev-local"
data:
  mongodb:
    uri: "mongodb://localhost:27017"

--- 

spring:
  profiles: "prod"
data:
  mongodb:
    uri: "mongodb://localhost:27017"
